---

test:
  service: TestUnit

rubygem:
  service : Gem
  exclude : [ log, pkg, web, doc/rdoc, doc/ri ]

rubyforge:
  service  : Rubyforge
  unixname : tigerops
  groupid  : 5881
  package  : richunits
  sitemap  : richunits

